# Generated by Django 4.2.13 on 2024-05-26 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='data',
            new_name='date',
        ),
    ]
